{% set version = "2018.3.3" %}

package:
  name: salt
  version: {{ version }}

source:
  fn: salt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/salt/salt-{{ version }}.tar.gz
  sha256: dcf30d2e8eae105a72977c51cfc253fbc4dc28b2f71277fdce9d35de1eb63e15

  patches:
    - setup.py.patch  # [win]

build:
  number: 0
  skip: True  # [win32]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jinja2
    - msgpack-python
    - openssl
    - pycrypto
    - pyyaml
    - pyzmq >=2.2.0
    - markupsafe
    - apache-libcloud
    - requests
    - tornado
    - pywin32  # [win]

test:
  commands:
    - salt --version  # [not win]
    - salt-minion --version

about:
  home: http://saltstack.com
  license: Apache 2.0
  summary: Software to automate the management and configuration of any infrastructure or application at scale

extra:
  recipe-maintainers:
    - basepi
    - danielfrg
    - nmadhok
