travis:
  secure:
    BINSTAR_TOKEN: amL7zjR+8sQ9Rfq8RXtQstUx0F3JIna79chPeeOme6qw4gxfwAPsHSCADvx4fYwnYXM7JAV8AiDGJ0mYfJ3ht/ICMekGpAoXxdoMGDd0mi+4C2ocAJCXTRNcwWMu2fCmyAPKjvAcVdMZmIliRDROwiTCiTK3P+2ALH2+GwkIBp0uwEAA8bUcZTnUhMndYx4GOasTzswfJfbY96t+iKkT5aEfjf4CUejr39l8F5AWx7bMu8VlQhcKgCP2qWptTnhpMbq6U5rrjsdPZV68vFFlJUchMmUVgdJiYsyO28hY29Sbygpvw+JT/EnGaXI0Tv4lVUd2MpYYpsqv6KyPh8Vq2swrdw4oL2SYmCGtMIwgeRc0osEH7x9zCsqj1rUPB/tZFwV5Yhlg2xB3riBh0YdRiKl3WqyKChXXOHjDZ20M81xROmLojrBOyi42Rnem2A4Hd2mTNpwW3t3Op2y44OhCHa9kKfe+E5qyfzoSzZ2W4AxUNdngK06fyqsyEnt2TawvAuNbjbnbS330P3LuKXmjFFsHUNKH9T4dPTf8N/SyqmM13iJrFL0MAX4FDKm8GtFedwwayCw3NZfvRwESfdEeD12SD7OWuSelQLDVU8Tp374qBTJVP676rEKpuVdC6i+jChdaxQCp3+5STTxEo3kQ/LGEnenE5PbQVK0WwBqhuuo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
